name: autonomy
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Try not to edit this section by hand. Use `dart pub add my_package`
dependencies:
  burt_network:
    git:
      url: https://github.com/BinghamtonRover/Networking.git
      ref: 2.3.0
  a_star: ^3.0.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^6.0.0
